// AUTO-GENERATED by tools/generate_ts_contracts.py
// Do not edit manually; run `npm run generate:api-types` instead.

export interface RestaurantListItem {
  id: string;
  name: string;
  cuisine?: string[];
  city: string;
  slug?: string | null;
  cover_photo?: string | null;
  timezone?: string | null;
  neighborhood?: string | null;
  address?: string | null;
  short_description?: string | null;
  price_level?: string | null;
  tags?: string[];
  tag_groups?: Record<string, string[]> | null;
  average_spend?: string | null;
  rating?: number | null;
  reviews_count?: number | null;
}

export interface Restaurant {
  id: string;
  name: string;
  slug?: string | null;
  cuisine?: string[];
  city?: string;
  timezone?: string;
  address?: string | null;
  phone?: string | null;
  photos?: string[];
  cover_photo?: string | null;
  short_description?: string | null;
  neighborhood?: string | null;
  price_level?: string | null;
  tags?: string[];
  tag_groups?: Record<string, string[]> | null;
  highlights?: string[];
  map_images?: string[];
  latitude?: number | null;
  longitude?: number | null;
  directions_url?: string | null;
  menu_url?: string | null;
  instagram?: string | null;
  whatsapp?: string | null;
  average_spend?: string | null;
  dress_code?: string | null;
  experiences?: string[];
  areas?: Area[];
  rating?: number | null;
  reviews_count?: number | null;
}

export interface Area {
  id: string;
  name?: string | null;
  tables?: Table[];
}

export interface Table {
  id: string;
  name?: string | null;
  capacity?: number;
  position?: [number, number] | null;
  shape?: "circle" | "rect" | "booth" | "pod" | null;
}

export interface Reservation {
  id: string;
  restaurant_id: string;
  party_size: number;
  start: string;
  end: string;
  guest_name: string;
  guest_phone?: string | null;
  table_id?: string | null;
  status?: "pending" | "booked" | "cancelled" | "arrived" | "no_show";
}

export interface ReservationCreate {
  restaurant_id: string;
  party_size: number;
  start: string;
  end: string;
  guest_name: string;
  guest_phone?: string | null;
  table_id?: string | null;
}

export interface Review {
  id: string;
  reservation_id: string;
  restaurant_id: string;
  rating: number;
  comment?: string | null;
  guest_name?: string | null;
  created_at?: string | null;
}
