import type { ImageSourcePropType } from 'react-native';
export type RestaurantAssetBundle = {
  cover?: ImageSourcePropType;
  gallery?: ImageSourcePropType[];
  pending?: boolean;
};

const bundle = (
  cover: ImageSourcePropType,
  gallery: ImageSourcePropType[],
): RestaurantAssetBundle => ({
  cover,
  gallery,
});

const pendingBundle = (): RestaurantAssetBundle => ({
  pending: true,
});

export const PENDING_PHOTO_SLUGS = new Set<string>([]);

export const restaurantPhotoManifest: Record<string, RestaurantAssetBundle> = {
  'abqorarestaurant': bundle(require('./restaurants/abqorarestaurant/1.webp'), [
    require('./restaurants/abqorarestaurant/1.webp'),
    require('./restaurants/abqorarestaurant/2.webp'),
    require('./restaurants/abqorarestaurant/3.webp'),
    require('./restaurants/abqorarestaurant/4.webp'),
    require('./restaurants/abqorarestaurant/5.webp'),
  ]),
  'abraudurso_baku': bundle(require('./restaurants/abraudurso-baku/1.webp'), [
    require('./restaurants/abraudurso-baku/1.webp'),
    require('./restaurants/abraudurso-baku/2.webp'),
    require('./restaurants/abraudurso-baku/3.webp'),
    require('./restaurants/abraudurso-baku/4.webp'),
    require('./restaurants/abraudurso-baku/5.webp'),
  ]),
  'adarestaurantbaku': bundle(require('./restaurants/adarestaurantbaku/1.webp'), [
    require('./restaurants/adarestaurantbaku/1.webp'),
    require('./restaurants/adarestaurantbaku/2.webp'),
    require('./restaurants/adarestaurantbaku/3.webp'),
    require('./restaurants/adarestaurantbaku/4.webp'),
    require('./restaurants/adarestaurantbaku/5.webp'),
  ]),
  'agabala.restaurant': bundle(require('./restaurants/agabala-restaurant/1.webp'), [
    require('./restaurants/agabala-restaurant/1.webp'),
    require('./restaurants/agabala-restaurant/2.webp'),
    require('./restaurants/agabala-restaurant/3.webp'),
    require('./restaurants/agabala-restaurant/4.webp'),
    require('./restaurants/agabala-restaurant/5.webp'),
  ]),
  'armoodbaku.az': bundle(require('./restaurants/armoodbaku-az/1.webp'), [
    require('./restaurants/armoodbaku-az/1.webp'),
    require('./restaurants/armoodbaku-az/2.webp'),
    require('./restaurants/armoodbaku-az/3.webp'),
    require('./restaurants/armoodbaku-az/4.webp'),
    require('./restaurants/armoodbaku-az/5.webp'),
  ]),
  'aurapark_restoran': bundle(require('./restaurants/aurapark-restoran/1.webp'), [
    require('./restaurants/aurapark-restoran/1.webp'),
    require('./restaurants/aurapark-restoran/2.webp'),
    require('./restaurants/aurapark-restoran/3.webp'),
    require('./restaurants/aurapark-restoran/4.webp'),
    require('./restaurants/aurapark-restoran/5.webp'),
  ]),
  'ayisigi__restaurant': bundle(require('./restaurants/ayisigi-restaurant/1.webp'), [
    require('./restaurants/ayisigi-restaurant/1.webp'),
  ]),
  'aynur.restoran.hotel': bundle(require('./restaurants/aynur-restoran-hotel/1.webp'), [
    require('./restaurants/aynur-restoran-hotel/1.webp'),
    require('./restaurants/aynur-restoran-hotel/2.webp'),
  ]),
  'badamdart_baku': bundle(require('./restaurants/badamdart-baku/1.webp'), [
    require('./restaurants/badamdart-baku/1.webp'),
    require('./restaurants/badamdart-baku/2.webp'),
    require('./restaurants/badamdart-baku/3.webp'),
    require('./restaurants/badamdart-baku/4.webp'),
    require('./restaurants/badamdart-baku/5.webp'),
  ]),
  'bahce_restoran': bundle(require('./restaurants/bahce-restoran/1.webp'), [
    require('./restaurants/bahce-restoran/1.webp'),
    require('./restaurants/bahce-restoran/2.webp'),
    require('./restaurants/bahce-restoran/3.webp'),
    require('./restaurants/bahce-restoran/4.webp'),
    require('./restaurants/bahce-restoran/5.webp'),
  ]),
  'bakucafe': bundle(require('./restaurants/baku-cafe/1.webp'), [
    require('./restaurants/baku-cafe/1.webp'),
    require('./restaurants/baku-cafe/2.webp'),
    require('./restaurants/baku-cafe/3.webp'),
    require('./restaurants/baku-cafe/4.webp'),
    require('./restaurants/baku-cafe/5.webp'),
  ]),
  'barin_baku': bundle(require('./restaurants/barin-baku/1.webp'), [
    require('./restaurants/barin-baku/1.webp'),
    require('./restaurants/barin-baku/2.webp'),
  ]),
  'beerbashabaku': bundle(require('./restaurants/beerbashabaku/1.webp'), [
    require('./restaurants/beerbashabaku/1.webp'),
    require('./restaurants/beerbashabaku/2.webp'),
    require('./restaurants/beerbashabaku/3.webp'),
    require('./restaurants/beerbashabaku/4.webp'),
    require('./restaurants/beerbashabaku/5.webp'),
  ]),
  'beerhallbayil': bundle(require('./restaurants/beerhallbayil/1.webp'), [
    require('./restaurants/beerhallbayil/1.webp'),
    require('./restaurants/beerhallbayil/2.webp'),
    require('./restaurants/beerhallbayil/3.webp'),
    require('./restaurants/beerhallbayil/4.webp'),
    require('./restaurants/beerhallbayil/5.webp'),
  ]),
  'bestplacebaku': bundle(require('./restaurants/bestplacebaku/1.webp'), [
    require('./restaurants/bestplacebaku/1.webp'),
    require('./restaurants/bestplacebaku/2.webp'),
    require('./restaurants/bestplacebaku/3.webp'),
    require('./restaurants/bestplacebaku/4.webp'),
    require('./restaurants/bestplacebaku/5.webp'),
  ]),
  'boulevard1909': bundle(require('./restaurants/boulevard1909/1.webp'), [
    require('./restaurants/boulevard1909/1.webp'),
    require('./restaurants/boulevard1909/2.webp'),
    require('./restaurants/boulevard1909/3.webp'),
    require('./restaurants/boulevard1909/4.webp'),
    require('./restaurants/boulevard1909/5.webp'),
  ]),
  'cafebotanist': bundle(require('./restaurants/cafebotanist/1.webp'), [
    require('./restaurants/cafebotanist/1.webp'),
    require('./restaurants/cafebotanist/2.webp'),
    require('./restaurants/cafebotanist/3.webp'),
    require('./restaurants/cafebotanist/4.webp'),
    require('./restaurants/cafebotanist/5.webp'),
  ]),
  'cay_evi_145': bundle(require('./restaurants/cay-evi-145/1.webp'), [
    require('./restaurants/cay-evi-145/1.webp'),
    require('./restaurants/cay-evi-145/2.webp'),
    require('./restaurants/cay-evi-145/3.webp'),
    require('./restaurants/cay-evi-145/4.webp'),
    require('./restaurants/cay-evi-145/5.webp'),
  ]),
  'caybagi145': bundle(require('./restaurants/caybagi145/1.webp'), [
    require('./restaurants/caybagi145/1.webp'),
    require('./restaurants/caybagi145/2.webp'),
    require('./restaurants/caybagi145/3.webp'),
    require('./restaurants/caybagi145/4.webp'),
    require('./restaurants/caybagi145/5.webp'),
  ]),
  'cennetbagishamakhi': bundle(require('./restaurants/cennetbagishamakhi/1.webp'), [
    require('./restaurants/cennetbagishamakhi/1.webp'),
    require('./restaurants/cennetbagishamakhi/2.webp'),
    require('./restaurants/cennetbagishamakhi/3.webp'),
    require('./restaurants/cennetbagishamakhi/4.webp'),
    require('./restaurants/cennetbagishamakhi/5.webp'),
  ]),
  'ceos_lounge_az': bundle(require('./restaurants/ceos-lounge-az/1.webp'), [
    require('./restaurants/ceos-lounge-az/1.webp'),
    require('./restaurants/ceos-lounge-az/2.webp'),
    require('./restaurants/ceos-lounge-az/3.webp'),
    require('./restaurants/ceos-lounge-az/4.webp'),
    require('./restaurants/ceos-lounge-az/5.webp'),
  ]),
  'chanaqqala': bundle(require('./restaurants/chanaqqala/1.webp'), [
    require('./restaurants/chanaqqala/1.webp'),
    require('./restaurants/chanaqqala/2.webp'),
    require('./restaurants/chanaqqala/3.webp'),
    require('./restaurants/chanaqqala/4.webp'),
    require('./restaurants/chanaqqala/5.webp'),
  ]),
  'chayki_restaurant': bundle(require('./restaurants/chayki-restaurant/1.webp'), [
    require('./restaurants/chayki-restaurant/1.webp'),
    require('./restaurants/chayki-restaurant/2.webp'),
    require('./restaurants/chayki-restaurant/3.webp'),
    require('./restaurants/chayki-restaurant/4.webp'),
    require('./restaurants/chayki-restaurant/5.webp'),
  ]),
  'chinardining': bundle(require('./restaurants/chinar/1.webp'), [
    require('./restaurants/chinar/1.webp'),
    require('./restaurants/chinar/2.webp'),
    require('./restaurants/chinar/3.webp'),
    require('./restaurants/chinar/4.webp'),
    require('./restaurants/chinar/5.webp'),
  ]),
  'cookshopbaku': bundle(require('./restaurants/cookshopbaku/1.webp'), [
    require('./restaurants/cookshopbaku/1.webp'),
    require('./restaurants/cookshopbaku/2.webp'),
    require('./restaurants/cookshopbaku/3.webp'),
    require('./restaurants/cookshopbaku/4.webp'),
    require('./restaurants/cookshopbaku/5.webp'),
  ]),
  'deryafishhouse': bundle(require('./restaurants/deryafishhouse/1.webp'), [
    require('./restaurants/deryafishhouse/1.webp'),
    require('./restaurants/deryafishhouse/2.webp'),
    require('./restaurants/deryafishhouse/3.webp'),
    require('./restaurants/deryafishhouse/4.webp'),
    require('./restaurants/deryafishhouse/5.webp'),
  ]),
  'des-baku': bundle(require('./restaurants/bestplacebaku/1.webp'), [
    require('./restaurants/bestplacebaku/1.webp'),
    require('./restaurants/bestplacebaku/2.webp'),
    require('./restaurants/bestplacebaku/3.webp'),
    require('./restaurants/bestplacebaku/4.webp'),
    require('./restaurants/bestplacebaku/5.webp'),
  ]),
  'des_baku': bundle(require('./restaurants/bestplacebaku/1.webp'), [
    require('./restaurants/bestplacebaku/1.webp'),
    require('./restaurants/bestplacebaku/2.webp'),
    require('./restaurants/bestplacebaku/3.webp'),
    require('./restaurants/bestplacebaku/4.webp'),
    require('./restaurants/bestplacebaku/5.webp'),
  ]),
  'dfnbaku': bundle(require('./restaurants/dfnbaku/1.webp'), [
    require('./restaurants/dfnbaku/1.webp'),
    require('./restaurants/dfnbaku/2.webp'),
    require('./restaurants/dfnbaku/3.webp'),
    require('./restaurants/dfnbaku/4.webp'),
    require('./restaurants/dfnbaku/5.webp'),
  ]),
  'dolivo.baku': bundle(require('./restaurants/dolivo-baku/1.webp'), [
    require('./restaurants/dolivo-baku/1.webp'),
    require('./restaurants/dolivo-baku/2.webp'),
    require('./restaurants/dolivo-baku/3.webp'),
    require('./restaurants/dolivo-baku/4.webp'),
    require('./restaurants/dolivo-baku/5.webp'),
  ]),
  'dolma.restaurant': bundle(require('./restaurants/dolma/1.webp'), [
    require('./restaurants/dolma/1.webp'),
    require('./restaurants/dolma/2.webp'),
    require('./restaurants/dolma/3.webp'),
    require('./restaurants/dolma/4.webp'),
    require('./restaurants/dolma/5.webp'),
  ]),
  'dukkan.khatai': bundle(require('./restaurants/dukkan-khatai/1.webp'), [
    require('./restaurants/dukkan-khatai/1.webp'),
    require('./restaurants/dukkan-khatai/2.webp'),
    require('./restaurants/dukkan-khatai/3.webp'),
    require('./restaurants/dukkan-khatai/4.webp'),
  ]),
  'dukkanorganic': bundle(require('./restaurants/dukkanorganic/1.webp'), [
    require('./restaurants/dukkanorganic/1.webp'),
    require('./restaurants/dukkanorganic/2.webp'),
    require('./restaurants/dukkanorganic/3.webp'),
  ]),
  'encir_restaurant': bundle(require('./restaurants/encir-restaurant/1.webp'), [
    require('./restaurants/encir-restaurant/1.webp'),
    require('./restaurants/encir-restaurant/2.webp'),
    require('./restaurants/encir-restaurant/3.webp'),
    require('./restaurants/encir-restaurant/4.webp'),
    require('./restaurants/encir-restaurant/5.webp'),
  ]),
  'firuzerestoran': bundle(require('./restaurants/firuze/1.webp'), [
    require('./restaurants/firuze/1.webp'),
    require('./restaurants/firuze/2.webp'),
    require('./restaurants/firuze/3.webp'),
    require('./restaurants/firuze/4.webp'),
    require('./restaurants/firuze/5.webp'),
  ]),
  'fishboxbaku': bundle(require('./restaurants/fishboxbaku/1.webp'), [
    require('./restaurants/fishboxbaku/1.webp'),
    require('./restaurants/fishboxbaku/2.webp'),
    require('./restaurants/fishboxbaku/3.webp'),
    require('./restaurants/fishboxbaku/4.webp'),
  ]),
  'fishhome.restaurant': bundle(require('./restaurants/fishhome-restaurant/1.webp'), [
    require('./restaurants/fishhome-restaurant/1.webp'),
    require('./restaurants/fishhome-restaurant/2.webp'),
    require('./restaurants/fishhome-restaurant/3.webp'),
    require('./restaurants/fishhome-restaurant/4.webp'),
    require('./restaurants/fishhome-restaurant/5.webp'),
  ]),
  'fisincanrestoran': bundle(require('./restaurants/fisincan-cafe/1.webp'), [
    require('./restaurants/fisincan-cafe/1.webp'),
    require('./restaurants/fisincan-cafe/2.webp'),
    require('./restaurants/fisincan-cafe/3.webp'),
    require('./restaurants/fisincan-cafe/4.webp'),
    require('./restaurants/fisincan-cafe/5.webp'),
  ]),
  'gunaydin.baku': bundle(require('./restaurants/gunaydin-baku/1.webp'), [
    require('./restaurants/gunaydin-baku/1.webp'),
    require('./restaurants/gunaydin-baku/2.webp'),
    require('./restaurants/gunaydin-baku/3.webp'),
    require('./restaurants/gunaydin-baku/4.webp'),
    require('./restaurants/gunaydin-baku/5.webp'),
  ]),
  'gutab_house': bundle(require('./restaurants/gutab-house/1.webp'), [
    require('./restaurants/gutab-house/1.webp'),
    require('./restaurants/gutab-house/2.webp'),
    require('./restaurants/gutab-house/3.webp'),
    require('./restaurants/gutab-house/4.webp'),
    require('./restaurants/gutab-house/5.webp'),
  ]),
  'hacibey_restoran_': bundle(require('./restaurants/hacibey-restoran/1.webp'), [
    require('./restaurants/hacibey-restoran/1.webp'),
    require('./restaurants/hacibey-restoran/2.webp'),
    require('./restaurants/hacibey-restoran/3.webp'),
    require('./restaurants/hacibey-restoran/4.webp'),
    require('./restaurants/hacibey-restoran/5.webp'),
  ]),
  'happymoonscafebaku': bundle(require('./restaurants/happymoonscafebaku/1.webp'), [
    require('./restaurants/happymoonscafebaku/1.webp'),
    require('./restaurants/happymoonscafebaku/2.webp'),
    require('./restaurants/happymoonscafebaku/3.webp'),
    require('./restaurants/happymoonscafebaku/4.webp'),
    require('./restaurants/happymoonscafebaku/5.webp'),
  ]),
  'harbourbaku': bundle(require('./restaurants/harbourbaku/1.webp'), [
    require('./restaurants/harbourbaku/1.webp'),
    require('./restaurants/harbourbaku/2.webp'),
    require('./restaurants/harbourbaku/3.webp'),
    require('./restaurants/harbourbaku/4.webp'),
    require('./restaurants/harbourbaku/5.webp'),
  ]),
  'ivandamariabaku': bundle(require('./restaurants/ivandamariabaku/1.webp'), [
    require('./restaurants/ivandamariabaku/1.webp'),
    require('./restaurants/ivandamariabaku/2.webp'),
    require('./restaurants/ivandamariabaku/3.webp'),
  ]),
  'ivarestaurantbaku': bundle(require('./restaurants/ivarestaurantbaku/1.webp'), [
    require('./restaurants/ivarestaurantbaku/1.webp'),
    require('./restaurants/ivarestaurantbaku/2.webp'),
    require('./restaurants/ivarestaurantbaku/3.webp'),
    require('./restaurants/ivarestaurantbaku/4.webp'),
    require('./restaurants/ivarestaurantbaku/5.webp'),
  ]),
  'junorestaurantbaku': bundle(require('./restaurants/junorestaurantbaku/1.webp'), [
    require('./restaurants/junorestaurantbaku/1.webp'),
    require('./restaurants/junorestaurantbaku/2.webp'),
    require('./restaurants/junorestaurantbaku/3.webp'),
  ]),
  'kababzadehrestaurant': bundle(require('./restaurants/kababzadehrestaurant/1.webp'), [
    require('./restaurants/kababzadehrestaurant/1.webp'),
    require('./restaurants/kababzadehrestaurant/2.webp'),
    require('./restaurants/kababzadehrestaurant/3.webp'),
    require('./restaurants/kababzadehrestaurant/4.webp'),
    require('./restaurants/kababzadehrestaurant/5.webp'),
  ]),
  'kaddehbaku': bundle(require('./restaurants/kaddehbaku/1.webp'), [
    require('./restaurants/kaddehbaku/1.webp'),
    require('./restaurants/kaddehbaku/2.webp'),
    require('./restaurants/kaddehbaku/3.webp'),
  ]),
  'khachapuri.land': bundle(require('./restaurants/khachapuri-land/1.webp'), [
    require('./restaurants/khachapuri-land/1.webp'),
    require('./restaurants/khachapuri-land/2.webp'),
    require('./restaurants/khachapuri-land/3.webp'),
    require('./restaurants/khachapuri-land/4.webp'),
    require('./restaurants/khachapuri-land/5.webp'),
  ]),
  'khachapuri.love': bundle(require('./restaurants/khachapuri-love/1.webp'), [
    require('./restaurants/khachapuri-love/1.webp'),
    require('./restaurants/khachapuri-love/2.webp'),
    require('./restaurants/khachapuri-love/3.webp'),
    require('./restaurants/khachapuri-love/4.webp'),
    require('./restaurants/khachapuri-love/5.webp'),
  ]),
  'khachapurihome': bundle(require('./restaurants/khachapurihome/1.webp'), [
    require('./restaurants/khachapurihome/1.webp'),
    require('./restaurants/khachapurihome/2.webp'),
    require('./restaurants/khachapurihome/3.webp'),
    require('./restaurants/khachapurihome/4.webp'),
    require('./restaurants/khachapurihome/5.webp'),
  ]),
  'kitchenplus_az': bundle(require('./restaurants/kitchenplus-az/1.webp'), [
    require('./restaurants/kitchenplus-az/1.webp'),
  ]),
  'koshque21': bundle(require('./restaurants/koshque21/1.webp'), [
    require('./restaurants/koshque21/1.webp'),
    require('./restaurants/koshque21/2.webp'),
    require('./restaurants/koshque21/3.webp'),
    require('./restaurants/koshque21/4.webp'),
    require('./restaurants/koshque21/5.webp'),
  ]),
  'leonebaku': bundle(require('./restaurants/leonebaku/1.webp'), [
    require('./restaurants/leonebaku/1.webp'),
    require('./restaurants/leonebaku/2.webp'),
    require('./restaurants/leonebaku/3.webp'),
    require('./restaurants/leonebaku/4.webp'),
    require('./restaurants/leonebaku/5.webp'),
  ]),
  'lviv.chocolate.baku': bundle(require('./restaurants/lviv-chocolate-baku/1.webp'), [
    require('./restaurants/lviv-chocolate-baku/1.webp'),
    require('./restaurants/lviv-chocolate-baku/2.webp'),
    require('./restaurants/lviv-chocolate-baku/3.webp'),
    require('./restaurants/lviv-chocolate-baku/4.webp'),
    require('./restaurants/lviv-chocolate-baku/5.webp'),
  ]),
  'maizebaku': bundle(require('./restaurants/maizebaku/1.webp'), [
    require('./restaurants/maizebaku/1.webp'),
    require('./restaurants/maizebaku/2.webp'),
    require('./restaurants/maizebaku/3.webp'),
    require('./restaurants/maizebaku/4.webp'),
    require('./restaurants/maizebaku/5.webp'),
  ]),
  'malacannes145': bundle(require('./restaurants/malacannes-145/1.webp'), [
    require('./restaurants/malacannes-145/1.webp'),
    require('./restaurants/malacannes-145/2.webp'),
    require('./restaurants/malacannes-145/3.webp'),
    require('./restaurants/malacannes-145/4.webp'),
    require('./restaurants/malacannes-145/5.webp'),
  ]),
  'malikhane_restaurant': bundle(require('./restaurants/malikhane-restaurant/1.webp'), [
    require('./restaurants/malikhane-restaurant/1.webp'),
    require('./restaurants/malikhane-restaurant/2.webp'),
  ]),
  'mamameri.restaurant': bundle(require('./restaurants/mamameri-restaurant/1.webp'), [
    require('./restaurants/mamameri-restaurant/1.webp'),
    require('./restaurants/mamameri-restaurant/2.webp'),
    require('./restaurants/mamameri-restaurant/3.webp'),
    require('./restaurants/mamameri-restaurant/4.webp'),
    require('./restaurants/mamameri-restaurant/5.webp'),
  ]),
  'mamounia_baku': bundle(require('./restaurants/mamounia-baku/1.webp'), [
    require('./restaurants/mamounia-baku/1.webp'),
    require('./restaurants/mamounia-baku/2.webp'),
    require('./restaurants/mamounia-baku/3.webp'),
    require('./restaurants/mamounia-baku/4.webp'),
    require('./restaurants/mamounia-baku/5.webp'),
  ]),
  'mangal_steak_house': bundle(require('./restaurants/mangal/1.webp'), [
    require('./restaurants/mangal/1.webp'),
    require('./restaurants/mangal/2.webp'),
    require('./restaurants/mangal/3.webp'),
    require('./restaurants/mangal/4.webp'),
    require('./restaurants/mangal/5.webp'),
  ]),
  'manifesto.az': bundle(require('./restaurants/manifesto-az/1.webp'), [
    require('./restaurants/manifesto-az/1.webp'),
    require('./restaurants/manifesto-az/2.webp'),
    require('./restaurants/manifesto-az/3.webp'),
    require('./restaurants/manifesto-az/4.webp'),
    require('./restaurants/manifesto-az/5.webp'),
  ]),
  'manzarabaku': bundle(require('./restaurants/manzarabaku/1.webp'), [
    require('./restaurants/manzarabaku/1.webp'),
    require('./restaurants/manzarabaku/2.webp'),
    require('./restaurants/manzarabaku/3.webp'),
    require('./restaurants/manzarabaku/4.webp'),
    require('./restaurants/manzarabaku/5.webp'),
  ]),
  'marani_azerbaijan': bundle(require('./restaurants/marani-azerbaijan/1.webp'), [
    require('./restaurants/marani-azerbaijan/1.webp'),
    require('./restaurants/marani-azerbaijan/2.webp'),
    require('./restaurants/marani-azerbaijan/3.webp'),
    require('./restaurants/marani-azerbaijan/4.webp'),
    require('./restaurants/marani-azerbaijan/5.webp'),
  ]),
  'marivanna_baku': bundle(require('./restaurants/marivanna/1.webp'), [
    require('./restaurants/marivanna/1.webp'),
    require('./restaurants/marivanna/2.webp'),
    require('./restaurants/marivanna/3.webp'),
    require('./restaurants/marivanna/4.webp'),
    require('./restaurants/marivanna/5.webp'),
  ]),
  'merci_baku': bundle(require('./restaurants/merci-baku/1.webp'), [
    require('./restaurants/merci-baku/1.webp'),
    require('./restaurants/merci-baku/2.webp'),
    require('./restaurants/merci-baku/3.webp'),
    require('./restaurants/merci-baku/4.webp'),
    require('./restaurants/merci-baku/5.webp'),
  ]),
  'metropol145': bundle(require('./restaurants/metropol-145/1.webp'), [
    require('./restaurants/metropol-145/1.webp'),
    require('./restaurants/metropol-145/2.webp'),
    require('./restaurants/metropol-145/3.webp'),
    require('./restaurants/metropol-145/4.webp'),
    require('./restaurants/metropol-145/5.webp'),
  ]),
  'mezze__baku': bundle(require('./restaurants/mezze-baku/1.webp'), [
    require('./restaurants/mezze-baku/1.webp'),
    require('./restaurants/mezze-baku/2.webp'),
    require('./restaurants/mezze-baku/3.webp'),
    require('./restaurants/mezze-baku/4.webp'),
  ]),
  'montenapoleonebaku': bundle(require('./restaurants/montenapoleonebaku/1.webp'), [
    require('./restaurants/montenapoleonebaku/1.webp'),
    require('./restaurants/montenapoleonebaku/2.webp'),
    require('./restaurants/montenapoleonebaku/3.webp'),
    require('./restaurants/montenapoleonebaku/4.webp'),
    require('./restaurants/montenapoleonebaku/5.webp'),
  ]),
  'movidabaku': bundle(require('./restaurants/movida-lounge-and-dining/1.webp'), [
    require('./restaurants/movida-lounge-and-dining/1.webp'),
    require('./restaurants/movida-lounge-and-dining/2.webp'),
    require('./restaurants/movida-lounge-and-dining/3.webp'),
    require('./restaurants/movida-lounge-and-dining/4.webp'),
    require('./restaurants/movida-lounge-and-dining/5.webp'),
  ]),
  'museuminnbaku': bundle(require('./restaurants/museuminnbaku/1.webp'), [
    require('./restaurants/museuminnbaku/1.webp'),
    require('./restaurants/museuminnbaku/2.webp'),
    require('./restaurants/museuminnbaku/3.webp'),
    require('./restaurants/museuminnbaku/4.webp'),
  ]),
  'nalbaki_baku': bundle(require('./restaurants/nalbaki-baku/1.webp'), [
    require('./restaurants/nalbaki-baku/1.webp'),
    require('./restaurants/nalbaki-baku/2.webp'),
    require('./restaurants/nalbaki-baku/3.webp'),
    require('./restaurants/nalbaki-baku/4.webp'),
    require('./restaurants/nalbaki-baku/5.webp'),
  ]),
  'nana_restaurant_az': bundle(require('./restaurants/nana-restaurant-az/1.webp'), [
    require('./restaurants/nana-restaurant-az/1.webp'),
    require('./restaurants/nana-restaurant-az/2.webp'),
    require('./restaurants/nana-restaurant-az/3.webp'),
  ]),
  'narsharab_restaurant': bundle(require('./restaurants/narsharab-restaurant/1.webp'), [
    require('./restaurants/narsharab-restaurant/1.webp'),
    require('./restaurants/narsharab-restaurant/2.webp'),
    require('./restaurants/narsharab-restaurant/3.webp'),
    require('./restaurants/narsharab-restaurant/4.webp'),
    require('./restaurants/narsharab-restaurant/5.webp'),
  ]),
  'nashadacha_restaurant': bundle(require('./restaurants/nashadacha-restaurant/1.webp'), [
    require('./restaurants/nashadacha-restaurant/1.webp'),
    require('./restaurants/nashadacha-restaurant/2.webp'),
    require('./restaurants/nashadacha-restaurant/3.webp'),
  ]),
  'natavan_restaurant': bundle(require('./restaurants/natavan-restaurant/1.webp'), [
    require('./restaurants/natavan-restaurant/1.webp'),
    require('./restaurants/natavan-restaurant/2.webp'),
    require('./restaurants/natavan-restaurant/3.webp'),
    require('./restaurants/natavan-restaurant/4.webp'),
  ]),
  'niaqara_restaurant': bundle(require('./restaurants/niaqara-restaurant/1.webp'), [
    require('./restaurants/niaqara-restaurant/1.webp'),
  ]),
  'nikkibeach.baku': bundle(require('./restaurants/nikkibeach-baku/1.webp'), [
    require('./restaurants/nikkibeach-baku/1.webp'),
    require('./restaurants/nikkibeach-baku/2.webp'),
    require('./restaurants/nikkibeach-baku/3.webp'),
    require('./restaurants/nikkibeach-baku/4.webp'),
    require('./restaurants/nikkibeach-baku/5.webp'),
  ]),
  'novikovcafe_baku': bundle(require('./restaurants/novikov/1.webp'), [
    require('./restaurants/novikov/1.webp'),
    require('./restaurants/novikov/2.webp'),
    require('./restaurants/novikov/3.webp'),
    require('./restaurants/novikov/4.webp'),
    require('./restaurants/novikov/5.webp'),
  ]),
  'oazis_park_restaurant': bundle(require('./restaurants/oazis-park-restaurant/1.webp'), [
    require('./restaurants/oazis-park-restaurant/1.webp'),
    require('./restaurants/oazis-park-restaurant/2.webp'),
    require('./restaurants/oazis-park-restaurant/3.webp'),
    require('./restaurants/oazis-park-restaurant/4.webp'),
    require('./restaurants/oazis-park-restaurant/5.webp'),
  ]),
  'ocakbasi_mangal': bundle(require('./restaurants/ocakbasi-mangal/1.webp'), [
    require('./restaurants/ocakbasi-mangal/1.webp'),
    require('./restaurants/ocakbasi-mangal/2.webp'),
    require('./restaurants/ocakbasi-mangal/3.webp'),
    require('./restaurants/ocakbasi-mangal/4.webp'),
    require('./restaurants/ocakbasi-mangal/5.webp'),
  ]),
  'organic__restaurant': bundle(require('./restaurants/organic-restaurant/1.webp'), [
    require('./restaurants/organic-restaurant/1.webp'),
    require('./restaurants/organic-restaurant/2.webp'),
    require('./restaurants/organic-restaurant/3.webp'),
    require('./restaurants/organic-restaurant/4.webp'),
    require('./restaurants/organic-restaurant/5.webp'),
  ]),
  'parkhouse.restaurant_': bundle(require('./restaurants/parkhouse-restaurant/1.webp'), [
    require('./restaurants/parkhouse-restaurant/1.webp'),
    require('./restaurants/parkhouse-restaurant/2.webp'),
    require('./restaurants/parkhouse-restaurant/3.webp'),
    require('./restaurants/parkhouse-restaurant/4.webp'),
    require('./restaurants/parkhouse-restaurant/5.webp'),
  ]),
  'pasificobaku': bundle(require('./restaurants/pasificobaku/1.webp'), [
    require('./restaurants/pasificobaku/1.webp'),
    require('./restaurants/pasificobaku/2.webp'),
    require('./restaurants/pasificobaku/3.webp'),
    require('./restaurants/pasificobaku/4.webp'),
    require('./restaurants/pasificobaku/5.webp'),
  ]),
  'paulazerbaijan': bundle(require('./restaurants/paulazerbaijan/1.webp'), [
    require('./restaurants/paulazerbaijan/1.webp'),
    require('./restaurants/paulazerbaijan/2.webp'),
    require('./restaurants/paulazerbaijan/3.webp'),
    require('./restaurants/paulazerbaijan/4.webp'),
    require('./restaurants/paulazerbaijan/5.webp'),
  ]),
  'plove_restaurant': bundle(require('./restaurants/plove-restaurant/1.webp'), [
    require('./restaurants/plove-restaurant/1.webp'),
    require('./restaurants/plove-restaurant/2.webp'),
    require('./restaurants/plove-restaurant/3.webp'),
    require('./restaurants/plove-restaurant/4.webp'),
    require('./restaurants/plove-restaurant/5.webp'),
  ]),
  'portbakujasmine': bundle(require('./restaurants/portbakujasmine/1.webp'), [
    require('./restaurants/portbakujasmine/1.webp'),
    require('./restaurants/portbakujasmine/2.webp'),
    require('./restaurants/portbakujasmine/3.webp'),
    require('./restaurants/portbakujasmine/4.webp'),
    require('./restaurants/portbakujasmine/5.webp'),
  ]),
  'prive_steak_gallery': bundle(require('./restaurants/prive-steak-gallery-baku/1.webp'), [
    require('./restaurants/prive-steak-gallery-baku/1.webp'),
    require('./restaurants/prive-steak-gallery-baku/2.webp'),
    require('./restaurants/prive-steak-gallery-baku/3.webp'),
    require('./restaurants/prive-steak-gallery-baku/4.webp'),
    require('./restaurants/prive-steak-gallery-baku/5.webp'),
  ]),
  'qala_divari': bundle(require('./restaurants/qala-divari/1.webp'), [
    require('./restaurants/qala-divari/1.webp'),
    require('./restaurants/qala-divari/2.webp'),
    require('./restaurants/qala-divari/3.webp'),
    require('./restaurants/qala-divari/4.webp'),
    require('./restaurants/qala-divari/5.webp'),
  ]),
  'qaynana_restaurant': bundle(require('./restaurants/qaynana/1.webp'), [
    require('./restaurants/qaynana/1.webp'),
    require('./restaurants/qaynana/2.webp'),
    require('./restaurants/qaynana/3.webp'),
    require('./restaurants/qaynana/4.webp'),
    require('./restaurants/qaynana/5.webp'),
  ]),
  'restaurantnuxa': bundle(require('./restaurants/restaurantnuxa/1.webp'), [
    require('./restaurants/restaurantnuxa/1.webp'),
    require('./restaurants/restaurantnuxa/2.webp'),
    require('./restaurants/restaurantnuxa/3.webp'),
    require('./restaurants/restaurantnuxa/4.webp'),
    require('./restaurants/restaurantnuxa/5.webp'),
  ]),
  'rivierabaku': bundle(require('./restaurants/riviera/1.webp'), [
    require('./restaurants/riviera/1.webp'),
    require('./restaurants/riviera/2.webp'),
    require('./restaurants/riviera/3.webp'),
    require('./restaurants/riviera/4.webp'),
    require('./restaurants/riviera/5.webp'),
  ]),
  'ruby360baku': bundle(require('./restaurants/ruby360baku/1.webp'), [
    require('./restaurants/ruby360baku/1.webp'),
    require('./restaurants/ruby360baku/2.webp'),
    require('./restaurants/ruby360baku/3.webp'),
    require('./restaurants/ruby360baku/4.webp'),
    require('./restaurants/ruby360baku/5.webp'),
  ]),
  'rustaveligeorgianrestaurant': bundle(require('./restaurants/rustaveligeorgianrestaurant/1.webp'), [
    require('./restaurants/rustaveligeorgianrestaurant/1.webp'),
    require('./restaurants/rustaveligeorgianrestaurant/2.webp'),
    require('./restaurants/rustaveligeorgianrestaurant/3.webp'),
    require('./restaurants/rustaveligeorgianrestaurant/4.webp'),
    require('./restaurants/rustaveligeorgianrestaurant/5.webp'),
  ]),
  'sahil_baku': bundle(require('./restaurants/sahil/1.webp'), [
    require('./restaurants/sahil/1.webp'),
    require('./restaurants/sahil/2.webp'),
    require('./restaurants/sahil/3.webp'),
    require('./restaurants/sahil/4.webp'),
    require('./restaurants/sahil/5.webp'),
  ]),
  'scalini_baku': bundle(require('./restaurants/scalini/1.webp'), [
    require('./restaurants/scalini/1.webp'),
    require('./restaurants/scalini/2.webp'),
    require('./restaurants/scalini/3.webp'),
    require('./restaurants/scalini/4.webp'),
    require('./restaurants/scalini/5.webp'),
  ]),
  'seabaybaku': bundle(require('./restaurants/seabaybaku/1.webp'), [
    require('./restaurants/seabaybaku/1.webp'),
  ]),
  'shefa_fish_garden': bundle(require('./restaurants/shefa-fish-garden/1.webp'), [
    require('./restaurants/shefa-fish-garden/1.webp'),
    require('./restaurants/shefa-fish-garden/2.webp'),
    require('./restaurants/shefa-fish-garden/3.webp'),
    require('./restaurants/shefa-fish-garden/4.webp'),
    require('./restaurants/shefa-fish-garden/5.webp'),
  ]),
  'sherlock_park': bundle(require('./restaurants/sherlock-park/1.webp'), [
    require('./restaurants/sherlock-park/1.webp'),
  ]),
  'shorehousebaku': bundle(require('./restaurants/shorehousebaku/1.webp'), [
    require('./restaurants/shorehousebaku/1.webp'),
    require('./restaurants/shorehousebaku/2.webp'),
    require('./restaurants/shorehousebaku/3.webp'),
    require('./restaurants/shorehousebaku/4.webp'),
    require('./restaurants/shorehousebaku/5.webp'),
  ]),
  'siesta_baku': bundle(require('./restaurants/siesta-baku/1.webp'), [
    require('./restaurants/siesta-baku/1.webp'),
    require('./restaurants/siesta-baku/2.webp'),
    require('./restaurants/siesta-baku/3.webp'),
  ]),
  'societebaku': bundle(require('./restaurants/societebaku/1.webp'), [
    require('./restaurants/societebaku/1.webp'),
    require('./restaurants/societebaku/2.webp'),
    require('./restaurants/societebaku/3.webp'),
    require('./restaurants/societebaku/4.webp'),
    require('./restaurants/societebaku/5.webp'),
  ]),
  'syrovarnya.baku': bundle(require('./restaurants/syrovarnya/1.webp'), [
    require('./restaurants/syrovarnya/1.webp'),
    require('./restaurants/syrovarnya/2.webp'),
    require('./restaurants/syrovarnya/3.webp'),
    require('./restaurants/syrovarnya/4.webp'),
    require('./restaurants/syrovarnya/5.webp'),
  ]),
  'tbilisirestoran_baku': bundle(require('./restaurants/tbilisirestoran-baku/1.webp'), [
    require('./restaurants/tbilisirestoran-baku/1.webp'),
    require('./restaurants/tbilisirestoran-baku/2.webp'),
    require('./restaurants/tbilisirestoran-baku/3.webp'),
    require('./restaurants/tbilisirestoran-baku/4.webp'),
    require('./restaurants/tbilisirestoran-baku/5.webp'),
  ]),
  'terrace.145': bundle(require('./restaurants/terrace-145/1.webp'), [
    require('./restaurants/terrace-145/1.webp'),
    require('./restaurants/terrace-145/2.webp'),
    require('./restaurants/terrace-145/3.webp'),
    require('./restaurants/terrace-145/4.webp'),
    require('./restaurants/terrace-145/5.webp'),
  ]),
  'thegallery_baku': bundle(require('./restaurants/thegallery-baku/1.webp'), [
    require('./restaurants/thegallery-baku/1.webp'),
    require('./restaurants/thegallery-baku/2.webp'),
    require('./restaurants/thegallery-baku/3.webp'),
    require('./restaurants/thegallery-baku/4.webp'),
    require('./restaurants/thegallery-baku/5.webp'),
  ]),
  'themoodbaku': bundle(require('./restaurants/themoodbaku/1.webp'), [
    require('./restaurants/themoodbaku/1.webp'),
    require('./restaurants/themoodbaku/2.webp'),
    require('./restaurants/themoodbaku/3.webp'),
    require('./restaurants/themoodbaku/4.webp'),
    require('./restaurants/themoodbaku/5.webp'),
  ]),
  'vasilchuki.baku': bundle(require('./restaurants/vasilchuki-baku/1.webp'), [
    require('./restaurants/vasilchuki-baku/1.webp'),
    require('./restaurants/vasilchuki-baku/2.webp'),
    require('./restaurants/vasilchuki-baku/3.webp'),
    require('./restaurants/vasilchuki-baku/4.webp'),
  ]),
  'villaturkishcuisine': bundle(require('./restaurants/villaturkishcuisine/1.webp'), [
    require('./restaurants/villaturkishcuisine/1.webp'),
    require('./restaurants/villaturkishcuisine/2.webp'),
    require('./restaurants/villaturkishcuisine/3.webp'),
    require('./restaurants/villaturkishcuisine/4.webp'),
    require('./restaurants/villaturkishcuisine/5.webp'),
  ]),
  'watergarden.restaurant': bundle(require('./restaurants/watergarden-restaurant/1.webp'), [
    require('./restaurants/watergarden-restaurant/1.webp'),
    require('./restaurants/watergarden-restaurant/2.webp'),
    require('./restaurants/watergarden-restaurant/3.webp'),
    require('./restaurants/watergarden-restaurant/4.webp'),
    require('./restaurants/watergarden-restaurant/5.webp'),
  ]),
  'yanardag_restaurant': bundle(require('./restaurants/yanardag-restaurant/1.webp'), [
    require('./restaurants/yanardag-restaurant/1.webp'),
    require('./restaurants/yanardag-restaurant/2.webp'),
    require('./restaurants/yanardag-restaurant/3.webp'),
    require('./restaurants/yanardag-restaurant/4.webp'),
    require('./restaurants/yanardag-restaurant/5.webp'),
  ]),
  'zilrestaurant': bundle(require('./restaurants/zilrestaurant/1.webp'), [
    require('./restaurants/zilrestaurant/1.webp'),
    require('./restaurants/zilrestaurant/2.webp'),
    require('./restaurants/zilrestaurant/3.webp'),
    require('./restaurants/zilrestaurant/4.webp'),
    require('./restaurants/zilrestaurant/5.webp'),
  ]),
};
